linters-settings:
  govet:
    enable-all: true
linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    # - import
    - metalinter
    # - module
    - performance
    # - sql
    - style
    - test
    - unused
  disable:
    - errcheck
    - depguard
    - goerr113
    - gci
    - gochecknoglobals
    - gomnd
    - nlreturn
    - varnamelen
    - wsl
