version: '2'
linters:
  default: all
  disable:
    - depguard
    - err113
    - errcheck
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - mnd
    - nlreturn
    - paralleltest
    - varnamelen
    - wsl
  settings:
    govet:
      enable-all: true
  exclusions:
    presets:
      - common-false-positives
      - legacy
    rules:
      - linters: [revive]
        path: example/
        text: '^package-comments: should have a package comment$'
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      rewrite-rules:
        - pattern: interface{}
          replacement: any
    gofumpt:
      extra-rules: true
