name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test (${{ matrix.goarch }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: windows-latest
            goarch: amd64
          - runner: windows-latest
            goarch: '386'
          - runner: windows-11-arm
            goarch: arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Run linter
        if: matrix.goarch == 'amd64'
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest

      - name: Run tests
        run: go test -v -coverpkg=./... ./...
        env:
          GOARCH: ${{ matrix.goarch }}
